version: "3"

services:
  syncthing:
    image: linuxserver/syncthing
    container_name: syncthing
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022
    volumes:
      - config-syncthing:/config
      - data-syncthing:/sync
    ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027/udp

volumes:
  data-syncthing:
    external: true
  config-syncthing:
    driver: local